### ISSUE TITLE
NoClassDefFoundError when building tranSMART Server

### ISSUE THREAD

**Issue by lukaszimmermann** [thehyve/transmart-core#404]
Item               | Version
--------------------|-----------
Git Commit    |`2a360fc00c6b0782681aab60e41b35bddcc98694`
Gradle            | 3.5 
JDK                 | 8
Docker Image |  gradle:3.5-jdk8-alpine 

When using 
```
gradle --no-daemon clean :transmart-server:assemble
```
in the Dockerfile:
```
https://github.com/lukaszimmermann/transmart-thehyve-docker/blob/develop/transmart-server/Dockerfile
```

the production deployment file
```
transmart-server-17.1-HYVE-5-SNAPSHOT.war
```
is built successfully, but the following exception is raised during `:transmart-server:assemble`:

```
Exception in thread "Thread-31" java.lang.NoClassDefFoundError: jline/console/history/MemoryHistory$EntriesIterator
	at jline.console.history.MemoryHistory.entries(MemoryHistory.java:152)
	at jline.console.history.MemoryHistory.entries(MemoryHistory.java:156)
	at jline.console.history.MemoryHistory.iterator(MemoryHistory.java:160)
	at jline.console.history.FileHistory.flush(FileHistory.java:89)
	at grails.build.logging.GrailsConsole.persistHistory(GrailsConsole.java:374)
	at grails.build.logging.GrailsConsole.beforeShutdown(GrailsConsole.java:351)
	at grails.build.logging.GrailsConsole$2.run(GrailsConsole.java:142)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: jline.console.history.MemoryHistory$EntriesIterator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```

To reproduce, please do:
```
git clone -b develop https://github.com/lukaszimmermann/transmart-thehyve-docker.git
docker build --no-cache --pull --rm transmart-thehyve-docker/transmart-server
```

Error is also present on your CI https://ci.ctmmtrait.nl/browse/TM-TMPRO0-BTW-203/log

**Comment by gijskant** [comment]
Hi Lucas, Thanks for reporting. I can reproduce the issue. It is also present here: https://travis-ci.org/thehyve/transmart-core/jobs/522082746#L2845. The image seems to be succesfully built and builds in general seem not to be affected by this issue in the build tool.
It won't have a high priority for us to fix.
Kind regards,
Gijs Kant
